
[package]
name = "lamport_mutex"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
