[package]
name = "byzantine_rust_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
